### PR TITLE
client: metadata requests sent to bootstrap nodes

### PR DESCRIPTION
**Pull request by gabriel-tincu**
We can avoid sending metadata requests to nodes that are no longer part
of the cluster if we always use the bootstrap node to send them, thus
ensuring we always have an up to date cluster metadata

### CODE REVIEW

**Comment by rikonen** [comment]
Won't this cause big discrepancy between cluster nodes when you have a lot of clients and all end up making metadata requests on same node?

**Comment by gabriel-tincu** [comment]
> Won't this cause big discrepancy between cluster nodes when you have a lot of clients and all end up making metadata requests on same node?

Probably yes, but i don't imagine that number to go beyond low double digits, and currently we have the refresh timer set to 60s. This is actually the least intrusive way to solve this issue (and it does seem to fix it). I'll look into some other approaches and compare the trade offs for the sake of argument

**Comment by rikonen** [comment]
> Probably yes, but i don't imagine that number to go beyond low double digits

Don't expect which number to go beyond low double digits? We have Kafka clusters with tens of thousands of connected clients and having any sort of requests always going to same broker doesn't sound great.

**Comment by gabriel-tincu** [comment]
> > Probably yes, but i don't imagine that number to go beyond low double digits
> 
> Don't expect which number to go beyond low double digits? We have Kafka clusters with tens of thousands of connected clients and having any sort of requests always going to same broker doesn't sound great.

This is only supposed to run inside the container, not outside. I would have figured that number to be more modest

**Comment by gabriel-tincu** [comment]
> > > Probably yes, but i don't imagine that number to go beyond low double digits
> > 
> > 
> > Don't expect which number to go beyond low double digits? We have Kafka clusters with tens of thousands of connected clients and having any sort of requests always going to same broker doesn't sound great.
> 
> This is only supposed to run inside the container, not outside. I would have figured that number to be more modest

OTOH... the safest way to go is probably to just patch the client for karapace, so I guess I'll approach this from a different angle

**Pull request closed without merging**
